---
title: "Plotting Growth Curves"
author: "UZH n UU: Who is the author here"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=TRUE, echo=FALSE}
library(readr) 
# this package is for loading files (e.g. tsv, csv, ..)

```


# Introduction

The data that we are going to use for this exercise is published in the mBio paper [@niggli2023mbio]. 
It can be found online on: https://doi.org/10.6084/m9.figshare.23578086.v1
It describes the OD600 (growth) of the *Staphylococcus aureus* strain **JE2** in different media.

# Reading in Data and Plotting Growth Curves

```{r load data, eval=TRUE, include=FALSE, echo=FALSE}
fN <- "JE_growth_final.txt" 
# us this txt file that is copy pasted spread sheet from excel tab separated 
#include=false does not show output
print(fN)
```

```{r print data, eval=TRUE, include=TRUE, echo=FALSE}
print("these are so called junks of code, you may include them to be shown in the rendered document (html here)
      each junk has a unique name next to it and then some additional arguments")
#include true shows output
print(fN)
```





# Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```


# References {-}

#show the dataframe first
```{r load data, eval=TRUE, include=TRUE, echo=FALSE}
data <- read.table("JE_growth_final.txt", header=TRUE, sep ="\t") 
#separated by tab characters, header true because first row contains column names
head(data, 10) #this will only show 10 first rows
tail(data, 10) #this will only show last 10 rows
```

#graph - basic plot
```{r load data, eval=TRUE, include=TRUE, echo=FALSE}
unique_medium <-unique(data$Growth_Medium)
print(unique_medium)

# Loop through each strain and plot separately
for (medium in unique_medium) {
  medium_data <- subset(data, Growth_Medium == medium)  # this separates the values for the three mediums into three different graphs
  
  
par(mar = c(2, 2, 2, 2) + 0.1)  #this is adjusting the margins for the graph
#the file JE_growth_final.txt has time and OD_600_blank_corrected as numerical values; we can make an x and y axis from that

plot(data$Time, data$OD600_blank_corrected, type = "o", xlab = "Time (hours)", ylab = "Growth ( Corrected OD600)", main = paste( "Growth Medium:", medium), col = "#4D7769")
}
```
